SMBL_FILE_IDs, = glob_wildcards("data/smbl/{id}.xml")

rule all:
    input: expand("results/smbl/{id}.json", id=SMBL_FILE_IDs)

rule transform_smbl_to_jsonld:
    input:
        "data/smbl/{record}.xml"
    output:
        "results/smbl/{record}.json"
    log:
        "logs/transform_smbl_to_jsonld.{record}.log"
    shell:
        "basex -bfile-path=../{input} scripts/smbl-tei-to-json.xq > {output} 2> {log}"